str = "Python"
print(str.isupper())
print(str.islower())
print(str.split())
print(str.isalpha())
print(str.capitalize())
print(str.replace("python","Java"))
print(len(str))
print(str.isdecimal())
print(str.isalnum())
print(str.casefold())
print(str.find('o'))
print(str.index('n'))
print(str + " Java")
print(str*10)
print(str.isidentifier())
print(str.swapcase())
print(str.isspace())